name: Examples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: justinjones/verilator:latest
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - name: Compile Verilog code
        run: verilator -cc -Wall -Isrc examples/basic/example.vlt examples/basic/tb.sv --assert --binary
      - name: Run testbench
        run: obj_dir/Vtb +verilator+error+limit+10 || true
