name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: justinjones/verilator:latest
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - name: Clone SVUnit
        uses: actions/checkout@v2
        with:
          repository: PeterMonsson/svunit
          ref: minimal-verilator
          path: svunit
      - name: runSVUnit
        run: (cd tests; SVUNIT_INSTALL=`pwd`/../svunit PATH=$PATH:$SVUNIT_INSTALL"/bin" runSVUnit -c_arg "-I../src" -c_arg "--assert" -c_arg "-j 0")
      - name: Check log
        run: '! grep "FAILED" tests/run.log; return $?;'
