name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: justinjones/verilator:latest
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - name: Clone SVUnit
        uses: actions/checkout@v2
        with:
          repository: PeterMonsson/svunit
          ref: add-verilator-support
          path: svunit
      - name: Compile Verilog code
        run: verilator -cc -Wno-WIDTHTRUNC -Isrc -f tests/.svunit.f --assert --binary
      - name: Run testbench
        run: obj_dir/Vjunit_xml +verilator+error+limit+10
