name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: justinjones/verilator:latest
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - name: Clone SVUnit
        uses: actions/checkout@v2
        with:
          repository: PeterMonsson/svunit
          ref: minimal-verilator
          path: svunit
      - name: Patch svunit_filter
        run: cd svunit; git checkout master -- svunit_base/svunit_filter.svh 
      - name: Compile Verilog code
        run: verilator -cc -Wno-WIDTHTRUNC -Isrc -f tests/.svunit.f --assert --binary
      - name: Run testbench
        run: obj_dir/Vjunit_xml +verilator+error+limit+10 | tee run.log
      - name: Check log
        run: '! grep "FAILED" run.log; return $?;'
