name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: justinjones/verilator:latest
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - name: Clone SVUnit
        uses: actions/checkout@v2
        with:
          repository: PeterMonsson/svunit
          ref: minimal-verilator
          path: svunit
      - name: Setup SVUnit
        run: (cd svunit/bin; source Setup.bsh)
      - name: runSVUnit
        run: (cd tests; runSVUnit -c_arg "-I../src" -c_arg "-Wno-WIDTHTRUNC" -c_arg "--assert"; obj_dir/Vtestrunner | tee obj_dir/run.log)
      - name: Check log
        run: '! grep "FAILED" tests/obj_dir/run.log; return $?;'
