name: Verilator Testbench

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: justinjones/verilator:latest
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - name: Clone SVUnit
        uses: actions/checkout@v2
        with:
          repository: svunit/svunit
          ref: master
          path: svunit
      - name: LS
        run: ls -al svunit
      - name: Compile Verilog code
        run: verilator -cc -Isrc examples/basic/tb.sv --assert --binary
      - name: Run testbench
        run: obj_dir/Vtb +verilator+error+limit+10
