name: Verilator Testbench

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: justinjones/verilator:latest
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - name: Compile Verilog code
        run: verilator -Wall -cc -Isrc examples/basic/tb.sv --binary
      - name: Run testbench
        run: obj_dir/Vtb
